simulation:
  base_case: "test_cases/cylinder_2D_Re100"
  startTime: 0
  duration: 1.0e-3
  writeInterval: 0.5
  deltaT: 1.0e-3
  gamg:
    smoother: "DICGaussSeidel"
    tolerance: 1e-06
    relTol: 0.01
    cacheAgglomeration: "yes"
    nCellsInCoarsestLevel: 10
    processorAgglomerator: "none"
    nPreSweeps: 0
    preSweepsLevelMultiplier: 1
    maxPreSweeps: 10
    nPostSweeps: 2
    postSweepsLevelMultiplier: 1
    maxPostSweeps: 10
    nFinestSweeps: 2
    interpolateCorrection: "no"
    scaleCorrection: "yes"
    directSolveCoarsest: "no"
    solverCoarsest: "PCG"
    preconditionerCoarsest: "DIC"
    toleranceCoarsest: 1e-06
    relTolCoarsest: 0.01

experiment:
  name: "cylinder2D-2"
  exp_path: "run/cylinder2D-2"
  launcher: "local"

optimization:
  startTime: [0]
  duration: 0.05
  writeInterval: 6
  deltaT: 1.0e-3
  repeat_trials: 2
  batch_size: 1
  bad_value: 0

